allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app")

    if (project.name == "isar_flutter_libs") {
        project.plugins.withId("com.android.library") {
            project.android {
                namespace "dev.isar.isar_flutter_libs"
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
